name: user_api_remote
description: User API Remote Package
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  rxdart: ^0.28.0
  shared_preferences: ^2.2.3
  tuple: ^2.0.2
  user_api:
    path: ../user_api

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^5.1.0
